### PR TITLE
Address warning-message

### LINKED ISSUE #103: Work around and remove `Active file is not package.json`
Hi @unional, hope you're well!

I often see the `Active file is not package.json` message (screenshot below) when I'm editing `package.json` and I click to another column, which triggers an auto-save.

Image

The message is coming from here:

https://github.com/unional/vscode-sort-package-json/blob/2f6db965f53a6763a5fe927f8ee601376924f96a/src/sortPackageJson.ts#L4-L8

Reproduction steps:

1. Configure auto-saving on focus change and `editor.codeActionsOnSave[number] = 'source.sortPackageJson'` in `settings.json`:
   ```json
   {
     "files.autoSave": "onFocusChange",
     "editor.codeActionsOnSave": {
       "source.sortPackageJson": "always"
     }
   }
   ```
2. Open 2 editor columns  `View` -> `Editor Layout` -> `Two Columns`
3. Open `package.json` in column 1 and a different file in column 2
4. Focus `package.json` and make a change
5. Focus the other file
6. 💥 Observe the warning message

This can occur for me multiple times per hour, if I'm making a lot of `package.json` edits quickly.

## Suggested Solution

My desired solution:

1. I would like to retain the `package.json` formatting while switching columns
2. I would like it to happen in the background
3. I would like no warning message to be shown

## Alternatives Considered

I'm aware that there is an alternative to sort only explicitly (only when I manually save):

```json
{
  "files.autoSave": "onFocusChange",
  "editor.codeActionsOnSave": {
    "source.sortPackageJson": "explicit"
  }
}
```

But this does not format when switching columns, my point 1 above.

### PR DESCRIPTION
**Pull request by unional**
fix #103

### CODE REVIEW

File: src/sortPackageJson.ts [hunk 1]
```diff
@@ -1,9 +1,11 @@
-import { Range, TextEditor, TextEditorEdit, window } from 'vscode'
+import { Range, TextEditor, TextEditorEdit } from 'vscode'
 import { getSortFn } from './getSortFn'
 
 export function sortPackageJson(textEditor: TextEditor, edit: TextEditorEdit) {
 	if (!textEditor.document.fileName.endsWith('package.json')) {
-		window.showWarningMessage('Active file is not package.json')
+		console.info(
+			`editor.sortPackageJson is invoked but active file is ${textEditor.document.fileName} and not package.json. This is a concurrency bug from vscode.`
+		)
```
Comment (karlhorky) [inline src/sortPackageJson.ts:8]: @unional great, thanks for this!

For anyone wondering what changed here, here is a video comparison between `unional.vscode-sort-package-json@1.5.3` and `unional.vscode-sort-package-json@1.5.4`:


https://github.com/user-attachments/assets/1a188779-1292-4582-8579-b5fcd0ef1936
